### ISSUE TITLE
where is readme

### ISSUE THREAD

**Issue by henbucuoshanghai** [akshaykadam771/Suspicious-Activity-Detection-Using-Pose-Estimation#3]
def readme():
    with open('README.md') as f:
        content = f.read()
    return content

in setup.py

**Comment by akshaykadam771** [comment]
Hi @henbucuoshanghai, this is the path for readme.md https://github.com/akshaykadam771/Suspicious-Activity-Detection-Using-Pose-Estimation/blob/main/README.md

**Comment by akshaykadam771** [comment]
#closed
